### PR TITLE
Refactor codebase

### PR DESCRIPTION
**Pull request by lukasdietrich**
Use configuration for many hard coded values.

### CODE REVIEW

**Comment by intOrfloat** [comment]
on the beta server i get this error 

- `data:    imageserver.js:9292 - /root/Anondraw_lukas/src/server/common/config.js:1`
- `data:    imageserver.js:9292 - (function (exports, require, module, __filename, __dirname) { let fs   = require("fs")`
- `data:    imageserver.js:9292 -                                                               ^^^`
- `data:    imageserver.js:9292 - SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode`

**Comment by lukasdietrich** [comment]
Was about to say, that node 4.2.3 is required. (see http://node.green/#let). *Latest* is a strong word though 😜

**Comment by intOrfloat** [comment]
it works great. running on [beta.anondraw.com](beta.anondraw.com) right now

**Comment by lukasdietrich** [comment]
Thanks for testing @intOrfloat ! 😄

**Pull request merged**
